<nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img class="logo" src="../img/c-logo1.png" width="50px" height="50px" alt="">
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="index.php">INICIO</a></li>
                    <li><a href="javascript.php">JAVASCRIPT</a></li>
                    <li><a href="php.php">PHP</a></li>
                </ul>
            </div>

        </div>
    </nav>